const TWITTER_CLIENT_ID = process.env.TWITTER_CLIENT_ID;
const TWITTER_CLIENT_SECRET = process.env.TWITTER_CLIENT_SECRET;
const REDIS_URL = process.env.REDIS_URL;

export { REDIS_URL, TWITTER_CLIENT_SECRET, TWITTER_CLIENT_ID };
